/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline';
import {OrthographicCamera} from '@react-three/drei';
import Character from "./Character";
import {useState} from "react";
import AnimatedText from "./AnimatedText";


export default function Scene({...props}) {
    const [ showText, setShowText ] = useState(false);

    const {nodes, materials} = useSpline('https://prod.spline.design/tm-q8M4UBVnlzfXs/scene.splinecode')


    return (
        <>
            <color attach="background" args={['#feeaea']}/>
            <group {...props} dispose={null}>
                <directionalLight
                    name="Directional Light"
                    intensity={0.7}
                    shadow-mapSize-width={1024}
                    shadow-mapSize-height={1024}
                    shadow-camera-near={-10000}
                    shadow-camera-far={100000}
                    shadow-camera-left={-1250}
                    shadow-camera-right={1250}
                    shadow-camera-top={1250}
                    shadow-camera-bottom={-1250}
                    position={[82.15, 265.23, 324.67]}
                />
                {/*<Character nodes={nodes} materials={materials} onClick={() => setShowText(true)}/>*/}
                <mesh
                    name="Floor"
                    geometry={nodes.Floor.geometry}
                    material={materials['Floor Material']}
                    castShadow
                    receiveShadow
                    position={[16.53, -248.45, 94.19]}
                    rotation={[-Math.PI / 2, 0, 0]}
                />
                <OrthographicCamera
                    name="1"
                    makeDefault={true}
                    far={2000}
                    near={0.01}
                    position={[0, 109.15, 894.03]}
                    rotation={[-0.11, 0, 0]}
                />
                <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" position={[0, 1, 0]}/>
            </group>
        </>
    )
}
